"""
Toy SCREENING analysis — the fixed-variable GATE read-out (HANDOFF §7/§8).

Post-processes the toy screening runs generated by make_toy_screening_scenarios.py
into two small interaction tables, and reports whether each swept axis interacts
with the axis held fixed in the matching Rotterdam slice. This is a SANDBOX
SCREENING, not a proof: a clear interaction means the held-fixed axis must be
crossed on Rotterdam instead of fixed (it changes the Rotterdam run-list).

  A) van-capacity x weight  (held alpha=1, peak): net_robust over van payload
     {750,1100,1400} x weight {light,heavy}. If the cap-effect shape differs by
     weight, capacity x weight interacts.
  B) total-N x alpha        (held medium, peak): net_robust over N {1000,4000} x
     alpha {0.5,1.0}. If net/N is not ~constant across alpha, N x alpha interacts.

net_robust = Term B - Term C (the quantities the toy resolves; Term A is seed
noise on the toy, HANDOFF §6). Means over the two seeds.

Run from project root (after the SCREEN runs finish):
    python python_pipeline/screening_analysis.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))

from parameters import RANDOM_SEEDS, WEIGHT_REGIMES, N_FREIGHT_UNITS_TOY
from run_pipeline import run_scenario
from sensitivity_surface import _find_events
from scenario_presets import get_preset
from make_toy_screening_scenarios import (
    VAN_PAYLOAD_CAPS, SCREEN_WEIGHTS, SCREEN_N, SCREEN_ALPHAS, OUT_BASE, CONGESTION)

preset = get_preset("toy")
RUNS = Path(OUT_BASE)
NETWORK = preset.network_file
_PRESET_KW = dict(
    sample_rate=preset.sample_rate,
    bus_trips_per_day=preset.bus_trips_per_day,
    transit_prefixes=preset.transit_prefixes,
    bus_id_allowlist=preset.term_c_bus_ids,
    hb_route_prefixes=preset.hb_route_prefixes,
    corridor_links_file=preset.corridor_links_file,
    n_pickup_stops=preset.n_pickup_stops,
    verbose=False,
)


def _events(run: str) -> Path | None:
    return _find_events(RUNS / run)


def _net_robust(baseline_run: str, scenario_run: str, alpha: float, weight: str,
                n_freight: int, cap: float | None) -> float | None:
    """Mean net_robust over seeds for one screening cell (skips missing runs)."""
    vals = []
    for seed in RANDOM_SEEDS:
        be = _events(f"{baseline_run}_seed{seed}")
        se = _events(f"{scenario_run}_seed{seed}")
        if be is None or se is None:
            continue
        res = run_scenario(
            baseline_events_path=str(be), network_path=NETWORK,
            scenario_events_path=str(se), alpha=alpha, weight_regime=weight,
            n_freight_units=n_freight, van_payload_capacity_kg=cap, **_PRESET_KW,
        )
        vals.append(res["net_robust_kg_per_day"])
    return sum(vals) / len(vals) if vals else None


def axis_a() -> pd.DataFrame:
    """van-capacity x weight at alpha=1, peak. Columns = van caps, rows = weights."""
    print("\n[Axis A] van-capacity x weight (alpha=1, peak) — net_robust kg/day")
    data = {}
    for weight in SCREEN_WEIGHTS:
        data[weight] = {}
        for cap in VAN_PAYLOAD_CAPS:
            base = f"screenA_cap{cap}_{weight}_alpha000_peak"
            net = _net_robust(base, "screenA_zerovan_peak", alpha=1.0, weight=weight,
                              n_freight=N_FREIGHT_UNITS_TOY, cap=cap)
            data[weight][cap] = net
    df = pd.DataFrame(data).T
    df.index.name = "weight"
    print(df.to_string(float_format=lambda v: f"{v:+.2f}"))
    # Interaction read-out: cap-effect (max cap vs min cap) per weight.
    lo, hi = min(VAN_PAYLOAD_CAPS), max(VAN_PAYLOAD_CAPS)
    print(f"\n  cap-effect net({hi}) - net({lo}) per weight:")
    for weight in SCREEN_WEIGHTS:
        a, b = df.loc[weight, lo], df.loc[weight, hi]
        if pd.notna(a) and pd.notna(b):
            print(f"    {weight:5s}: {b - a:+.2f} kg/day "
                  f"({'flat' if abs(b - a) < 1 else 'capacity matters'})")
    print("  -> if one weight is flat and the other is not, capacity x weight INTERACTS "
          "(run the Rotterdam van-capacity slice at a binding weight, do not fix arbitrarily).")
    return df


def axis_b() -> pd.DataFrame:
    """total-N x alpha at medium weight, peak. Columns = alpha, rows = N."""
    print("\n[Axis B] total-N x alpha (medium, peak) — net_robust kg/day")
    data = {}
    for N in SCREEN_N:
        data[N] = {}
        for alpha in SCREEN_ALPHAS:
            astr = f"{int(alpha * 100):03d}"
            base = f"screenB_N{N}_medium_alpha000_peak"
            scen = f"screenB_N{N}_medium_alpha{astr}_peak"
            net = _net_robust(base, scen, alpha=alpha, weight="medium", n_freight=N, cap=None)
            data[N][alpha] = net
    df = pd.DataFrame(data).T
    df.index.name = "N"
    print(df.to_string(float_format=lambda v: f"{v:+.2f}"))
    # Interaction read-out: net per 1000 parcels at each alpha; ~constant => no interaction.
    print("\n  net per 1000 parcels (net / N x 1000) at each alpha:")
    for alpha in SCREEN_ALPHAS:
        per = [(df.loc[N, alpha] / N * 1000) for N in SCREEN_N if pd.notna(df.loc[N, alpha])]
        if per:
            spread = max(per) - min(per)
            print(f"    alpha={alpha:.2f}: " + ", ".join(f"{p:+.2f}" for p in per)
                  + f"  (spread {spread:.2f})")
    print("  -> if net/N is ~constant across N within each alpha, N scales linearly and "
          "N x alpha does NOT interact (fixing N in the Rotterdam alpha-slice is safe).")
    return df


def main() -> None:
    a = axis_a()
    b = axis_b()
    out = Path("output/screening")
    out.mkdir(parents=True, exist_ok=True)
    a.to_csv(out / "screening_axisA_vancap_weight.csv")
    b.to_csv(out / "screening_axisB_N_alpha.csv")
    print(f"\nWrote tables -> {out}/screening_axis{{A,B}}_*.csv")
    print("Reminder: this is a sandbox SCREENING (toy), not a proof. Report it as such.")


if __name__ == "__main__":
    main()
